# Generated by Django 5.1 on 2024-12-03 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100)),
                ('no_of_beds', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ward_img', models.CharField(max_length=255)),
                ('ward_details', models.TextField()),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('partially_occupied', 'Partially Occupied'), ('fully_occupied', 'Fully Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='vacant', max_length=50)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='bed_management.ward')),
            ],
        ),
    ]
