# Generated by Django 5.1.3 on 2024-12-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hospital_hosp_password'),
        ('bed_management', '0002_ward_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mobile', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('prescription', models.FileField(upload_to='prescriptions/')),
                ('booking_date', models.DateField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_management.ward')),
            ],
        ),
    ]
