# Generated by Django 5.1.3 on 2024-12-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0003_bedbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedbooking',
            name='user_mobile',
        ),
    ]
