# Generated by Django 5.1.3 on 2024-12-07 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hospital_hosp_password'),
        ('bed_management', '0004_remove_bedbooking_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
                ('admission_letter', models.FileField(upload_to='admission_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='admitted', max_length=20)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_management.bed')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_management.ward')),
            ],
        ),
    ]
