# Generated by Django 5.1.3 on 2024-12-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0005_patientadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='no_of_beds',
            field=models.IntegerField(default=0),
        ),
    ]
