# Generated by Django 5.1.3 on 2024-12-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0006_alter_ward_no_of_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateField()),
                ('discharge_document', models.FileField(upload_to='discharge_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bed_management.patientadmission')),
            ],
        ),
    ]
