# Generated by Django 5.1.3 on 2024-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0008_remove_patientdischarge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischarge',
            name='discharge_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
