# Generated by Django 5.1.3 on 2024-12-08 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0009_alter_patientdischarge_discharge_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField()),
                ('death_certificate', models.FileField(upload_to='death_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bed_management.patientadmission')),
            ],
            options={
                'db_table': 'death_records',
            },
        ),
    ]
