# Generated by Django 5.1.3 on 2024-12-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management', '0010_deathrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='occupation_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='release_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
