# Generated by Django 5.1 on 2024-12-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0002_opdbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
