# Generated by Django 5.1 on 2024-12-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0004_alter_opdbooking_doctor_id_alter_slot_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='online_hours',
            field=models.DurationField(null=True),
        ),
    ]
