# Generated by Django 5.1 on 2024-12-10 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0007_walkinslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walkinslot',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='walkinslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walkinslot',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='walkinslot',
            name='token_number',
            field=models.IntegerField(),
        ),
    ]
