# Generated by Django 5.1 on 2024-12-10 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0008_alter_walkinslot_options_walkinslot_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walkinslot',
            options={'ordering': ['token_number']},
        ),
        migrations.AddField(
            model_name='walkinslot',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
