# Generated by Django 5.1 on 2024-12-10 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_management', '0009_alter_walkinslot_options_walkinslot_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTokenTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_token', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_tracker', to='doctor_management.doctor')),
            ],
        ),
    ]
