# Generated by Django 5.1 on 2024-12-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='expiry_date',
            new_name='Inv_expiry_date',
        ),
    ]
