# Generated by Django 5.1 on 2024-12-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_rename_inv_expiry_date_inventory_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='expiry_date',
        ),
    ]
