# Generated by Django 5.1 on 2024-12-02 10:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hosp_ID', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Hospital Unique ID')),
                ('hosp_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Hospital Name')),
                ('hosp_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Hospital Email')),
                ('hosp_contact_no', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Contact Number')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Hospital Logo URL')),
                ('hosp_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('hosp_log', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('hosp_address', models.TextField(verbose_name='Complete Address')),
                ('hosp_no_of_beds', models.PositiveIntegerField(verbose_name='Number of Beds')),
                ('hosp_password', models.CharField(max_length=255, verbose_name='Hashed Password')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['-created_at'],
            },
        ),
    ]
