# Generated by Django 5.1 on 2024-12-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar',
            field=models.IntegerField(max_length=12, null=True, unique=True),
        ),
    ]
