# Generated by Django 5.2.4 on 2025-07-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_user_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
