# Generated by Django 5.1.3 on 2024-12-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govschemes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentscheme',
            old_name='health_problems',
            new_name='healthProblems',
        ),
        migrations.RenameField(
            model_name='governmentscheme',
            old_name='scheme_name',
            new_name='schemeName',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='age',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='family_size',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='scheme_description',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='scheme_url',
        ),
        migrations.RemoveField(
            model_name='governmentscheme',
            name='state',
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='familySize',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='maritalStatus',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='schemeDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='schemeUrl',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='userAge',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='userState',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='caste',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='income',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
