# Generated by Django 5.1.3 on 2024-12-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govschemes', '0002_rename_health_problems_governmentscheme_healthproblems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentscheme',
            name='caste',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='familySize',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='gender',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='income',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='maritalStatus',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='userAge',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='userState',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
